version: "3"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1

  # Inpired by: https://github.com/Netflix/osstracker/blob/master/docker-compose.yml
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:4.1
    depends_on:
      - cassandra
    volumes:
      - ./cassandra-init.cql:/init.cql
    command: /bin/bash -c "sleep 40 && echo loading cassandra keyspace && cqlsh cassandra -f /init.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
